"""Render and check the RTGENACE modernization traceability matrix.

docs/modernization/rtgenace/traceability.json maps every specified behaviour of the
legacy task to the Fortran lines it comes from, the ported code that implements it,
the tests and corpus savecases that prove it, and the divergences and review
findings that changed it. This tool checks that every reference still resolves
(Fortran anchors on their lines, Python symbols, test functions, corpus cases) and
renders TRACEABILITY.md, including the parity evidence in modernization.json.

Usage:
    python tools/build_traceability.py           # validate and write TRACEABILITY.md
    python tools/build_traceability.py --check   # fail if references or render are stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs" / "modernization" / "rtgenace"
MATRIX = DOCS / "traceability.json"
RENDERED = DOCS / "TRACEABILITY.md"
GOLDEN = REPO / "legacy" / "habitat" / "characterization" / "rtgenace" / "golden.json"
MODERNIZATION = REPO / "console" / "public" / "modernization.json"
SHA_RE = re.compile(r"[0-9a-f]{40}")


def _symbol_defined(source: str, symbol: str) -> bool:
    name = re.escape(symbol)
    return bool(
        re.search(rf"^(def|class) {name}\b|^{name}\s*[:=]", source, re.MULTILINE)
    )


def problems(doc: dict) -> list[str]:
    found: list[str] = []
    cases = set(json.loads(GOLDEN.read_text()))
    history = {entry["id"]: entry for entry in doc["history"]}
    traced_cases: set[str] = set()
    for req in doc["requirements"]:
        rid = req["id"]
        for ref in req["legacy"]:
            path = REPO / ref["file"]
            if not path.is_file():
                found.append(f"{rid}: missing legacy file {ref['file']}")
                continue
            first, last = ref["lines"]
            span = "\n".join(path.read_text().splitlines()[first - 1 : last])
            if ref["anchor"] not in span:
                found.append(
                    f"{rid}: '{ref['anchor']}' not on {ref['file']}:{first}-{last}"
                )
        for ref in req["modern"]:
            file, _, symbol = ref.partition("::")
            path = REPO / file
            if not path.is_file() or not _symbol_defined(path.read_text(), symbol):
                found.append(f"{rid}: {ref} not defined")
        for ref in req["tests"]:
            file, _, func = ref.partition("::")
            path = REPO / file
            if not path.is_file() or f"def {func}(" not in path.read_text():
                found.append(f"{rid}: test {ref} not found")
        for case in req["cases"]:
            if case not in cases:
                found.append(f"{rid}: corpus case {case} not in golden.json")
            traced_cases.add(case)
        for hid in req["history"]:
            if hid not in history:
                found.append(f"{rid}: history entry {hid} not recorded")
    for case in sorted(cases - traced_cases):
        if not case.startswith("random_"):
            found.append(
                f"hand-picked corpus case {case} is not traced to a requirement"
            )
    for entry in doc["history"]:
        if entry["commit"] is not None and not SHA_RE.fullmatch(entry["commit"]):
            found.append(f"{entry['id']}: commit must be a full SHA or null")
    return found


def _link(file: str, lines: list[int] | None = None) -> str:
    target = "../../../" + file + (f"#L{lines[0]}-L{lines[1]}" if lines else "")
    label = Path(file).name + (f":{lines[0]}-{lines[1]}" if lines else "")
    return f"[{label}]({target})"


def render(doc: dict) -> str:
    parity = json.loads(MODERNIZATION.read_text())["parity"]
    corpus = parity["corpus"]
    out = [
        f"# {doc['task']} traceability matrix (spec v{doc['spec_version']})",
        "",
        "<!-- Generated by tools/build_traceability.py from traceability.json. Do not edit. -->",
        "",
        "Each row traces one behaviour from [SPEC.md](SPEC.md) to the legacy Fortran it comes",
        "from, the port that implements it, and the evidence that proves the two agree.",
        "`--check` (run by `backend/tests/test_rtgenace_traceability.py`) fails when a",
        "Fortran anchor moves, a symbol or test is renamed, or a hand-picked corpus case",
        "is not traced.",
        "",
        "## Requirements",
        "",
        "| ID | Behaviour | Legacy | Port | Tests | Corpus cases | History |",
        "|---|---|---|---|---|---|---|",
    ]
    for req in doc["requirements"]:
        legacy = "<br>".join(_link(r["file"], r["lines"]) for r in req["legacy"])
        modern = "<br>".join(
            f"`{Path(r.split('::')[0]).name}::{r.split('::')[1]}`"
            for r in req["modern"]
        )
        tests = "<br>".join(f"`{r.split('::')[1]}`" for r in req["tests"])
        cases = ", ".join(f"`{c}`" for c in req["cases"]) or "n/a"
        hist = ", ".join(req["history"]) or "n/a"
        out.append(
            f"| **{req['id']}** | {req['statement']} | {legacy} | {modern} | {tests} | {cases} | {hist} |"
        )
    out += [
        "",
        "## Change history",
        "",
        "D = divergence between the old Python and the Fortran, found by characterization",
        "before the port. F = automated review finding on the PR.",
        "",
        "| ID | Kind | What was wrong | Resolution | Commit |",
        "|---|---|---|---|---|",
    ]
    for entry in doc["history"]:
        commit = entry["commit"]
        ref = (
            f"[`{commit[:7]}`]({doc['pull_request']}/commits/{commit})"
            if commit
            else "n/a"
        )
        out.append(
            f"| {entry['id']} | {entry['kind']} | {entry['summary']} | {entry['resolution']} | {ref} |"
        )
    out += [
        "",
        "## Current parity evidence",
        "",
        "From `console/public/modernization.json` (written by `tools/build_legacy_inventory.py`).",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Production savecase | `{parity['savecase']}` |",
        f"| Legacy / port ACE | {parity['legacy_ace_mw']} / {parity['modern_ace_mw']} MW |",
        f"| Production ACE delta / derived bound | {parity['max_abs_delta_mw']} / {parity['ace_bound_mw']} MW |",
        f"| Corpus | {corpus['cases']} savecases ({corpus['accepted']} accepted, {corpus['refused']} refused) |",
        f"| Goldens reproduced by the legacy binary | {corpus['goldens_reproduced']}/{corpus['cases']} |",
        f"| Port matches legacy | {corpus['matched']}/{corpus['cases']} |",
        f"| Worst ACE delta / bound use | {corpus['max_ace_delta_mw']} MW / {corpus['worst_bound_use_pct']}% |",
        f"| Deadband knife-edge cases | {corpus['deadband_indeterminate']} |",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    doc = json.loads(MATRIX.read_text())
    found = problems(doc)
    for problem in found:
        print(f"traceability: {problem}", file=sys.stderr)
    if found:
        return 1
    text = render(doc)
    if args.check:
        if not RENDERED.is_file() or RENDERED.read_text() != text:
            print(
                "traceability: TRACEABILITY.md is stale; run tools/build_traceability.py",
                file=sys.stderr,
            )
            return 1
        print(f"traceability: {len(doc['requirements'])} requirements resolve")
        return 0
    RENDERED.write_text(text)
    print(
        f"traceability: wrote {RENDERED.relative_to(REPO)} ({len(doc['requirements'])} requirements)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
