"""Capture characterization goldens for the legacy RTGENACE task.

Writes a corpus of savecase exports to legacy/habitat/characterization/rtgenace/cases/
and records what the gfortran-built RTGENACE binary prints for each one (stdout and
exit status) in golden.json. The corpus is the production savecase, hand-picked
operating points that exercise every branch of RPTACE, ALLOCR and HDB_READ_EXPORT,
and seeded random operating points. Re-running the tool is deterministic.

Usage:
    python tools/capture_rtgenace_golden.py           # regenerate cases and goldens
    python tools/capture_rtgenace_golden.py --check   # fail if goldens are stale
"""

from __future__ import annotations

import argparse
import json
import random
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LEGACY = REPO / "legacy" / "habitat"
BINARY = LEGACY / "build" / "rtgenace"
CORPUS = LEGACY / "characterization" / "rtgenace"
CASES = CORPUS / "cases"
GOLDEN = CORPUS / "golden.json"
PRODUCTION_SAVECASE = LEGACY / "savecases" / "rtnet_ems_0742.export"

SEED = 742
RANDOM_CASES = 40

Tie = tuple[str, float, float]
UnitRow = tuple[str, float, float, float, float, float, bool]

HARBOR: list[UnitRow] = [
    ("GEN.HARBOR1", 212.0, 120.0, 260.0, 6.0, 0.45, True),
    ("GEN.HARBOR2", 188.5, 120.0, 260.0, 6.0, 0.35, True),
    ("GEN.MESQUITE_CT", 44.0, 20.0, 120.0, 18.0, 0.20, True),
    ("GEN.CEDAR_STM", 305.0, 240.0, 340.0, 3.0, 0.00, False),
]


def export(
    name: str,
    freq: tuple[float, float, float] = (60.0, 60.0, -412.0),
    ties: list[Tie] | None = None,
    meterr: float = 0.0,
    units: list[UnitRow] | None = None,
    after_end: str = "",
) -> str:
    fa, fs, bias = freq
    lines = [
        "* Characterization savecase for RTGENACE, generated by",
        "* tools/capture_rtgenace_golden.py. Do not edit by hand.",
        "CLONE    RTNET.EMS",
        f"SAVECASE {name}",
        "TIMESTAMP 2026-02-11T07:42:00Z",
        "RECORD FREQ",
        f"  AREA.CEDARVALLEY   {fa:.4f}  {fs:.4f}  {bias:.1f}  N",
        "RECORD TIELINE",
    ]
    for tie_id, actual, sched in ties if ties is not None else []:
        lines.append(f"  {tie_id:<18} {actual:.3f}  {sched:.3f}  N")
    lines += ["RECORD METERR", f"  AREA.CEDARVALLEY   {meterr:.2f}", "RECORD UNIT"]
    for unit_id, mw, lo, hi, ramp, pf, agc in units if units is not None else HARBOR:
        flag = "T" if agc else "F"
        lines.append(f"  {unit_id:<18} {mw:.2f} {lo:.2f} {hi:.2f} {ramp:.2f} {pf:.3f} {flag}")
    lines.append("END")
    text = "\n".join(lines) + "\n"
    return text + after_end


def ties_for(delta_mw: float) -> list[Tie]:
    """Three tie lines whose net interchange error is `delta_mw`."""
    return [("TIE.NORTH340", 400.0 + delta_mw, 400.0), ("TIE.EAST115", -140.0, -140.0),
            ("TIE.SOUTH230", 105.0, 105.0)]


def hand_picked() -> dict[str, str]:
    cases: dict[str, str] = {}
    cases["production_rtnet_ems_0742"] = PRODUCTION_SAVECASE.read_text(encoding="utf-8")

    cases["deadband_inside"] = export("DEADBAND_INSIDE", ties=ties_for(3.2))
    cases["deadband_edge_positive"] = export("DEADBAND_EDGE_POS", ties=ties_for(7.5), meterr=2.5)
    cases["deadband_edge_negative"] = export("DEADBAND_EDGE_NEG", ties=ties_for(-2.5), meterr=2.5)
    cases["just_outside_deadband"] = export("OUTSIDE_DEADBAND", ties=ties_for(5.5))
    cases["unclipped_share"] = export(
        "UNCLIPPED",
        ties=ties_for(-6.0),
        units=[("GEN.A", 200.0, 100.0, 300.0, 60.0, 0.5, True),
               ("GEN.B", 150.0, 100.0, 300.0, 60.0, 0.5, True)],
    )
    cases["over_generation_ramp_clip"] = export("OVERGEN_RAMP", ties=ties_for(180.0))
    cases["under_generation_ramp_clip"] = export("UNDERGEN_RAMP", ties=ties_for(-180.0))
    cases["clamp_at_max"] = export(
        "CLAMP_MAX",
        ties=ties_for(-40.0),
        units=[("GEN.PEAKER", 119.5, 20.0, 120.0, 30.0, 1.0, True)],
    )
    cases["clamp_at_min"] = export(
        "CLAMP_MIN",
        ties=ties_for(40.0),
        units=[("GEN.BASE", 240.4, 240.0, 340.0, 30.0, 1.0, True)],
    )
    cases["unit_above_max"] = export(
        "ABOVE_MAX",
        ties=ties_for(-20.0),
        units=[("GEN.OVERRUN", 275.0, 120.0, 260.0, 6.0, 1.0, True)],
    )
    cases["unit_below_min"] = export(
        "BELOW_MIN",
        ties=ties_for(20.0),
        units=[("GEN.STARTING", 90.0, 120.0, 260.0, 6.0, 1.0, True)],
    )
    cases["min_above_max_limits"] = export(
        "BAD_LIMITS",
        ties=ties_for(-30.0),
        units=[("GEN.BADLIMITS", 150.0, 200.0, 180.0, 60.0, 1.0, True)],
    )
    cases["no_units_on_agc"] = export(
        "NO_AGC",
        ties=ties_for(-50.0),
        units=[(u[0], u[1], u[2], u[3], u[4], u[5], False) for u in HARBOR],
    )
    cases["zero_participation"] = export(
        "ZERO_PF",
        ties=ties_for(-50.0),
        units=[(u[0], u[1], u[2], u[3], u[4], 0.0, True) for u in HARBOR],
    )
    cases["negative_participation_excluded"] = export(
        "NEG_PF",
        ties=ties_for(-50.0),
        units=[("GEN.A", 200.0, 100.0, 300.0, 60.0, 0.6, True),
               ("GEN.B", 200.0, 100.0, 300.0, 60.0, -0.4, True),
               ("GEN.C", 200.0, 100.0, 300.0, 60.0, 0.4, True)],
    )
    cases["frequency_only"] = export("FREQ_ONLY", freq=(59.95, 60.0, -412.0), ties=[])
    cases["high_frequency"] = export("HIGH_FREQ", freq=(60.035, 60.0, -880.0), ties=ties_for(4.0))
    cases["meter_error_only"] = export("METERR_ONLY", ties=ties_for(0.0), meterr=-12.5)
    cases["off_nominal_schedule"] = export(
        "TLB_SCHED", freq=(59.982, 59.98, -412.0), ties=ties_for(-9.0)
    )
    cases["deadband_float32_knife_edge"] = export(
        "KNIFE_EDGE", freq=(59.968, 60.0, -412.0), ties=ties_for(136.843)
    )

    reordered = (
        "CLONE    RTNET.EMS\nSAVECASE REORDERED\n"
        "RECORD UNIT\n"
        "  GEN.A  200.0 100.0 300.0 30.0 0.7 T\n"
        "  GEN.B  180.0 100.0 300.0 30.0 0.3 T\n"
        "\n*  comment between records\n\n"
        "RECORD METERR\n  AREA.CEDARVALLEY  1.0\n"
        "RECORD TIELINE\n  TIE.NORTH340  380.0  400.0  N\n"
        "RECORD FREQ\n  AREA.CEDARVALLEY  60.010  60.000  -412.0  N\n"
        "END\n"
    )
    cases["records_reordered_with_comments"] = reordered
    cases["records_after_end_ignored"] = export(
        "AFTER_END",
        ties=ties_for(-30.0),
        after_end="RECORD UNIT\n  GEN.GHOST  100.0 50.0 200.0 30.0 5.0 T\n",
    )
    cases["unknown_record_skipped"] = export("UNKNOWN_REC", ties=ties_for(-30.0)).replace(
        "RECORD UNIT", "RECORD BREAKER\n  CB.1201  CLOSED  N\nRECORD UNIT"
    )
    cases["malformed_unit_row"] = export("MALFORMED", ties=ties_for(-30.0)).replace(
        "GEN.HARBOR2        188.50 120.00 260.00 6.00 0.350 T", "GEN.HARBOR2        188.50 120.00"
    )
    cases["non_numeric_tieline"] = export("NON_NUMERIC", ties=ties_for(-30.0)).replace(
        "TIE.EAST115        -140.000", "TIE.EAST115        OFFSCAN"
    )
    cases["unit_table_overflow"] = export(
        "UNIT_OVERFLOW",
        ties=ties_for(-30.0),
        units=[(f"GEN.U{i:02d}", 50.0, 10.0, 90.0, 6.0, 0.01, True) for i in range(65)],
    )
    cases["unit_table_full"] = export(
        "UNIT_FULL",
        ties=ties_for(-30.0),
        units=[(f"GEN.U{i:02d}", 50.0, 10.0, 90.0, 6.0, 0.01, True) for i in range(64)],
    )
    cases["tieline_table_overflow"] = export(
        "TIE_OVERFLOW", ties=[(f"TIE.T{i:02d}", 10.0, 9.5) for i in range(33)]
    )
    return cases


def float32_ace_estimate(fa: float, fs: float, bias: float, dtie: float, meterr: float) -> float:
    return dtie - 10.0 * bias * (fa - fs) - meterr


def random_cases(rng: random.Random) -> dict[str, str]:
    cases: dict[str, str] = {}
    while len(cases) < RANDOM_CASES:
        index = len(cases) + 1
        bias = -round(rng.uniform(40.0, 1500.0), 1)
        fs = rng.choice([60.0, 60.0, 60.0, 59.98, 60.02])
        fa = round(fs + rng.gauss(0.0, 0.015), 3)
        ties = []
        for t in range(rng.randint(1, 5)):
            sched = round(rng.uniform(-400.0, 400.0), 1)
            ties.append((f"TIE.R{t:02d}", round(sched + rng.gauss(0.0, 12.0), 1), sched))
        meterr = round(rng.uniform(-6.0, 6.0), 2)
        dtie = sum(a - s for _, a, s in ties)
        ace = float32_ace_estimate(fa, fs, bias, dtie, meterr)
        # Keep the random corpus off the deadband edge; knife-edge points are pinned
        # explicitly by the hand-picked deadband cases.
        if abs(abs(ace) - 5.0) < 0.25:
            continue
        units = []
        for u in range(rng.randint(1, 8)):
            lo = round(rng.uniform(10.0, 250.0), 1)
            hi = round(lo + rng.uniform(20.0, 300.0), 1)
            mw = round(rng.uniform(lo - 10.0, hi + 10.0), 1)
            ramp = round(rng.uniform(1.0, 30.0), 1)
            pf = round(rng.choice([0.0, rng.uniform(0.0, 0.6), rng.uniform(0.0, 0.6)]), 3)
            units.append((f"GEN.R{u:02d}", mw, lo, hi, ramp, pf, rng.random() > 0.15))
        cases[f"random_{index:03d}"] = export(
            f"RANDOM_{index:03d}", freq=(fa, fs, bias), ties=ties, meterr=meterr, units=units
        )
    return cases


def build_binary() -> None:
    if shutil.which("gfortran") is None:
        sys.exit("gfortran is required to capture RTGENACE goldens")
    subprocess.run(["make", "--silent", "FC=gfortran", "all"], cwd=LEGACY, check=True)


def run_legacy(path: Path) -> dict[str, object]:
    proc = subprocess.run([str(BINARY), str(path)], capture_output=True, text=True, check=False)
    return {"exit_code": proc.returncode, "stdout": proc.stdout.splitlines()}


def corpus() -> dict[str, str]:
    cases = hand_picked()
    cases.update(random_cases(random.Random(SEED)))
    return cases


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    args = parser.parse_args()

    build_binary()
    cases = corpus()
    if args.check:
        expected = json.loads(GOLDEN.read_text(encoding="utf-8"))
        stale = [
            name
            for name, text in cases.items()
            if (CASES / f"{name}.export").read_text(encoding="utf-8") != text
            or run_legacy(CASES / f"{name}.export") != expected.get(name)
        ]
        if stale or set(expected) != set(cases):
            sys.exit(f"stale RTGENACE goldens: {stale or sorted(set(expected) ^ set(cases))}")
        print(f"{len(cases)} RTGENACE goldens match the legacy binary")
        return

    if CASES.exists():
        shutil.rmtree(CASES)
    CASES.mkdir(parents=True)
    golden: dict[str, dict[str, object]] = {}
    for name, text in sorted(cases.items()):
        path = CASES / f"{name}.export"
        path.write_text(text, encoding="utf-8")
        golden[name] = run_legacy(path)
    GOLDEN.write_text(json.dumps(golden, indent=1) + "\n", encoding="utf-8")
    refused = sum(1 for g in golden.values() if g["exit_code"] != 0)
    print(f"captured {len(golden)} RTGENACE goldens ({refused} refused by the legacy reader)")


if __name__ == "__main__":
    main()
